In [40]:
import pandas as pd
dataset=pd.read_csv("PrePlacement.csv")
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [41]:
dataset.drop("sl_no",inplace=True,axis=1)

In [42]:
dataset

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [43]:
dataset.isnull().sum()

ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [44]:
qual=[colname for colname in dataset if dataset[colname].dtypes == "O"]
quan=[colname for colname in dataset if dataset[colname].dtypes !="O"]

In [45]:
quan , qual

(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [46]:
from scipy.stats import ttest_ind
male=dataset[dataset['hsc_s']=='M']['salary']
Female=dataset[dataset['hsc_s']=='F']['salary']
ttest_ind(male,Female)

C:\Anaconda3\Lib\site-packages\scipy\_lib\deprecation.py:234: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return f(*args, **kwargs)

TtestResult(statistic=np.float64(nan), pvalue=np.float64(nan), df=np.float64(nan))

In [47]:
## T value 1.90 

#0 → very strong evidence (big difference)
#1 → no evidence (no difference)

## P-Value 0.05

# p < 0.05 → ✅ Significant
# p ≥ 0.05 → ❌ Not significant

#| Test        | When to use                                |
#| ----------- | ------------------------------------------ |
#| `ttest_ind` | 2 different groups (Male vs Female)        |
#| `ttest_rel` | Same people (before vs after, SSLC vs HSC) |

In [48]:
## Paried T Test
##Same group (male) different condition 

from scipy.stats import ttest_rel
male=dataset[dataset['gender']=='M']['ssc_p']
male1=dataset[dataset['gender']=='M']['etest_p']
ttest_ind(male,male1)

TtestResult(statistic=np.float64(-4.32383322751101), pvalue=np.float64(2.1438967270863995e-05), df=np.float64(276.0))

In [49]:
## p Value 
## p = 2.92e-08 that means 0.0000000292  -- > so p < 0.05 p-value is extremely small
## t-value = -4.32 Big magnitude → strong difference , Negative sign → second group mean > first group mean

## -- > There is a statistically significant difference between the two groups, and the second group has higher values than the first group.

In [50]:
##Same group (commerece ) different condition  ( mba_p , etest_p)

from scipy.stats import ttest_rel
com1=dataset[dataset['hsc_s']=='Commerce']['mba_p']
com2=dataset[dataset['hsc_s']=='Commerce']['etest_p']
ttest_rel(com1,com2)

TtestResult(statistic=np.float64(-7.868552092606871), pvalue=np.float64(2.462926468454984e-12), df=np.int64(112))

In [51]:
##There is a highly statistically significant difference between MBA marks and Entrance test scores for Commerce students.
## E-test scores > MBA scores

# HYPOTHESIS

In [52]:
###  Test whether MBA mark of commerce and entrance test make of commerce student make is same ?
### Null Hypothesis (H₀) ( or) Alternative Hypothesis (H₁)

from scipy.stats import ttest_rel
com1=dataset[dataset['hsc_s']=='Commerce']['mba_p']
com2=dataset[dataset['hsc_s']=='Commerce']['etest_p']
ttest_rel(com1,com2)

TtestResult(statistic=np.float64(-7.868552092606871), pvalue=np.float64(2.462926468454984e-12), df=np.int64(112))

In [53]:
## p-value = 2.46e-12 =  2.46e-12 < 0.05 
## There is a statistically significant difference between MBA and entrance test scores.
""" Since p-value < 0.05, we reject the null hypothesis. There is a statistically significant difference between MBA 
and entrance test scores for Commerce students, and entrance test scores are higher than MBA scores."""

' Since p-value < 0.05, we reject the null hypothesis. There is a statistically significant difference between MBA \nand entrance test scores for Commerce students, and entrance test scores are higher than MBA scores.'