In [1]:
import pandas as pd
dataset =pd.read_csv("PrePlacement.csv")
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [2]:
dataset.drop("sl_no",inplace=True,axis=1)

In [3]:
dataset

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

# One Way ANOVA ( Analysis of Variance )

In [5]:
from scipy.stats import f_oneway
one_way=f_oneway(dataset['ssc_p'],dataset['hsc_p'],dataset['degree_p'])
one_way

F_onewayResult(statistic=np.float64(0.6719700864663096), pvalue=np.float64(0.5110602818995302))

In [7]:
from scipy.stats import f_oneway
commerce = dataset[dataset['hsc_s'] == 'Commerce']['mba_p']
science = dataset[dataset['hsc_s'] == 'Science']['mba_p']
arts = dataset[dataset['hsc_s'] == 'Arts']['mba_p']

f_oneway(commerce, science, arts)

F_onewayResult(statistic=np.float64(0.2664227347184184), pvalue=np.float64(0.7663713172687782))

In [ ]:
#| Item      | Meaning                   |
#| --------- | ------------------------- |
#| p = 0.766 | No significant difference |
#| F = 0.266 | Very low variation        |
#| Result    | All groups similar        |

#| F value               | Meaning              |
#| --------------------- | -------------------- |
#| Small F (≈ 1 or less) | groups are similar   |
#| Large F               | groups are different |

"""F is very small , So groups are almost same , No strong difference """

""" p = 0.766  -- > 0.766 > 0.05 ===== #So :  We fail to reject H₀"""

## We do not have evidence to say groups are different, so we keep the Null Hypothesis.

## Two Way ANOVA

In [8]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Example: Dependent variable = mba_p
# Factors = hsc_s (High School Stream), gender

# Build the model
model = ols('mba_p ~ C(hsc_s) + C(gender) + C(hsc_s):C(gender)', data=dataset).fit()

# Perform Two-Way ANOVA
anova_table = sm.stats.anova_lm(model, typ=2)
print(anova_table)



# mba_p → Dependent variable (MBA percentage).
# C(hsc_s) → Factor 1 (High School stream, categorical).
# C(gender) → Factor 2 (Gender, categorical).
# C(hsc_s):C(gender) → Interaction effect (does stream effect depend on gender?).
# anova_lm(model, typ=2) → Gives ANOVA table with:
# sum_sq → Sum of squares (variance explained).
# df → Degrees of freedom.
# F → F‑statistic.
# PR(>F) → p‑value (significance).

                         sum_sq     df          F    PR(>F)
C(hsc_s)              28.116580    2.0   0.451822  0.637088
C(gender)            667.569125    1.0  21.455116  0.000006
C(hsc_s):C(gender)    93.277552    2.0   1.498931  0.225760
Residual            6502.968683  209.0        NaN       NaN

In [ ]:
## Gender → significant factor influencing MBA percentage.
## High School Stream → not significant.
## Interaction (HSC Stream × Gender) → not significant.

## So, for your dataset, gender is the only factor that matters statistically for MBA percentage. Stream doesn’t add explanatory power.